
// This script is automatically generated by MAGES. Do not modify or remove.
// >>I2VbdL6+HzDTEIk/GgUXqA==<<
namespace MAGES.Token
{
    using UnityEngine;
    public class TokenPreload : MonoBehaviour
    {
        private void Awake()
        {
            System.Type[] entries = new System.Type[]
            {
	// Hub: Enable Non Web Microphone API
	#if UNITY_STANDALONE_WIN||UNITY_STANDALONE_OSX||UNITY_STANDALONE_LINUX||UNITY_IOS||UNITY_ANDROID||UNITY_VISIONOS
	typeof(MAGES.NonWebMicrophone.Token),
	#endif // UNITY_STANDALONE_WIN||UNITY_STANDALONE_OSX||UNITY_STANDALONE_LINUX||UNITY_IOS||UNITY_ANDROID||UNITY_VISIONOS
	// Hub: Enable Web Microphone API
	#if UNITY_WEBGL
	typeof(MAGES.WebMicrophone.Token),
	#endif // UNITY_WEBGL

            };
        }
    }
}

